#
# Copyright 2013-2024 the original author or authors from the JHipster project.
#
# This file is part of the JHipster project, see https://www.jhipster.tech/
# for more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Setup Runner for JHipster Applications
inputs:
  node-version:
    description: Node version to be installed.
  java-version:
    description: Java version to be installed.
  npm-version:
    description: npm version to be installed.
  npm-cache:
    description: Restore npm cache.
    default: true
  maven-cache:
    description: Restore maven cache.
    default: false
  gradle-cache:
    description: Restore gradle cache.
    default: false
  binary-dir:
    description: Path to the dir containing the executable
  remove-android:
    default: true
    description: Remove dotnet to free space
  remove-dotnet:
    default: true
    description: Remove dotnet to free space
  remove-java:
    default: false
    description: Remove java to free space
runs:
  using: composite
  steps:
    - uses: jhipster/actions/create-app-path@v0
    - uses: jhipster/actions/setup-keycloak-hostname@v0
    - uses: jhipster/actions/setup-git@v0
    - uses: actions/setup-node@v4
      if: inputs.node-version
      with:
        node-version: ${{ inputs.node-version }}
    - uses: actions/setup-java@v4
      if: inputs.java-version
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java-version }}
    - name: 'Install required NPM version'
      if: inputs.npm-version
      shell: bash
      run: npm install -g npm@${{ inputs.npm-version }} || true
    - uses: jhipster/actions/restore-cache@v0
      with:
        npm: ${{ inputs.npm-cache }}
        maven: ${{ inputs.maven-cache }}
        gradle: ${{ inputs.gradle-cache }}
    - run: echo "${{ inputs.binary-dir }}" >> $GITHUB_PATH
      shell: bash
      if: inputs.binary-dir
    - name: 'Remove Android'
      if: inputs.remove-android
      shell: bash
      run: rm -rf /usr/local/lib/android
    - name: 'Remove .Net'
      if: inputs.remove-dotnet
      shell: bash
      run: rm -rf /usr/share/dotnet
    - name: 'Remove Java'
      if: inputs.remove-dotnet
      shell: bash
      run: sudo rm -rf /usr/lib/jvm
