name: compare-sample
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cmd:
          - jhipster --defaults --skip-install
          - jhipster --unknown-opt
    steps:
      - uses: actions/checkout@v5
        with:
          path: jhipster-actions
          fetch-depth: 1
      - uses: ./jhipster-actions/create-app-path
      - uses: ./jhipster-actions/setup-git
      - uses: actions/checkout@v5
        with:
          path: generator-jhipster
          repository: jhipster/generator-jhipster
          ref: v8.0.0
          fetch-depth: 2
      - uses: actions/setup-node@v6
        with:
          node-version: 20
      - uses: ./jhipster-actions/restore-cache
        with:
          npm: true
      - run: npm install && npm link
        working-directory: ${{ github.workspace }}/generator-jhipster
      - run: echo "$PATH"
      - run: npx generator-jhipster@8.0.0-rc.1 --defaults --skip-install
        working-directory: ${{ github.workspace }}/app
      - uses: ./jhipster-actions/compare-sample
        with:
          generator-path: generator-jhipster
          cmd: ${{ matrix.cmd }}
