name: create-app-path
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v5
        with:
          path: jhipster-actions
          fetch-depth: 1
      - uses: ./jhipster-actions/create-app-path
      - run: pwd
        working-directory: ${{ github.workspace }}/app
